var app=(function(){var $appHeight=$(window).height();$("section").css("height",$appHeight);$("#background_image").css("height",$appHeight+200);$("#background_image2").css("height",$appHeight+200);$("#background_image2").css("top",$appHeight+200);$('#main_nav').on('click','a',function(event){event.preventDefault();$('html, body').animate({scrollTop:$($.attr(this,'href')).offset().top},2000);menu.toggleClass("hidden");burger1.toggleClass('burger_nav_expand_1');burger2.toggleClass('burger_nav_expand_2')});var menu=$("#menu"),burgerMenu=$('#burger_menu'),burger1=$("#burger_1"),burger2=$('#burger_2');$("#nav>a").on("click",function(){menu.toggleClass("hidden");burger1.toggleClass('burger_nav_expand_1');burger2.toggleClass('burger_nav_expand_2')})
burgerMenu.on("click",function(){menu.toggleClass("hidden");burger1.toggleClass('burger_nav_expand_1');burger2.toggleClass('burger_nav_expand_2')})
function parallalex(){var offSet=-(window.pageYOffset/4)+"px";document.getElementById("parallalex_background").style.transform="translate3d(0px, "+offSet+", 0)"}
function makeStuffSEOfriendly(){$('img').attr("alt","pain4pleasure flo gropper tattoo")}
window.addEventListener('scroll',parallalex,!1);var init=function(){console.log("app.init!")
mod_home.bindEvents();mod_gallery.bindEvents();mod_contact.bindEvents();mod_footer.bindEvents();app.makeStuffSEOfriendly()};return{init:init,makeStuffSEOfriendly:makeStuffSEOfriendly}})();var mod_home=(function(){function bindEvents(){}
function blur(){document.querySelector('.home_bgimage').classList.toggle("homeblur")}
return{bindEvents:bindEvents}})();var mod_about=(function(){var caption=$("#about1_caption"),text=$("#about1_text"),image=$("#about_image"),caption2=$("#about2_caption"),text2=$("#about2_text"),caption3=$("#about3_caption"),text3=$("#about3_text"),caption4=$("#contact_caption"),text4=$("#contact_text");$.ajax({url:"assets/text/about.json",dataType:"json",success:function(response){console.log(response);data=response;caption.html(data.about.caption);text.html(data.about.paragraph);caption2.html(data.style.caption);text2.html(data.style.paragraph);caption3.html(data.termin.caption);text3.html(data.termin.paragraph);caption4.html(data.motiv.caption);text4.html(data.motiv.paragraph)}})})();var mod_gallery=(function(){$.ajax({url:"assets/text/images.json",dataType:"json",success:function(response){images=response.midRes;thumbs=response.thumbs;loadThumbs()}});var currentImage=0,currentThumb=5,ImagesAdded=6,count=0;var path="http://pain4pleasure.de/web/assets/images/tattoos/midRes/",path2="http://pain4pleasure.de/web/assets/images/tattoos/thumbs/";var $gallery=$("#gallery");var img1=document.getElementById("image"),img2=document.getElementById("image2");var images=[],thumbs=[];function displaySelectedImage(e){currentImage=thumbs.indexOf(e.target.src.substring(path2.length,e.target.length));var p=""+path+images[currentImage]+"";if($('.color')){$('.color').toggleClass("blackngrey");$('.color').toggleClass("color")}
e.target.classList.toggle('blackngrey');e.target.classList.toggle('color');$(".gallery_image:not(.hidden)").toggleClass("hidden");$("img[src='"+p+"']").toggleClass("hidden")}
function displayImage(){var p=""+path+images[currentImage]+"";$(".gallery_image:not(.hidden)").toggleClass("hidden");$("img[src='"+p+"']").toggleClass("hidden")}
function markThumbSelected(){$(".color").toggleClass("color").toggleClass("blackngrey");$("img[src='"+path2+thumbs[currentImage]+"']").toggleClass("color").toggleClass("blackngrey");document.getElementById("gallery_thumb_container").style.transform="translate3d("+(-90*currentImage)+"px,"+"0,"+"0)"}
function loadImagesNext(){console.log(currentImage);if(currentImage<images.length-1){currentImage++}else{currentImage=0}
loadImages();displayImage();markThumbSelected()}
function loadImagesPrevious(){console.log(currentImage);if(currentImage>0){currentImage--}else{currentImage=images.length-1}
loadImages();displayImage();markThumbSelected()}
function loadImages(){var count2=ImagesAdded;if(ImagesAdded<images.length){count2+=7;for(var i=ImagesAdded;i<count2;i++){var image=document.createElement('img');image.src=path+i+"_mid.jpg";image.name=""+i;image.classList.add("gallery_image","hidden");document.getElementById("image_view").appendChild(image);ImagesAdded++}}else{}}
function loadThumbs(){var ctn=$("#gallery_thumb_container");for(var i=0;i<thumbs.length;++i){var $thumb=$('<img class="image_thumb blackngrey">');if(i==0){$thumb.addClass("color");$thumb.removeClass("blackngrey")}
var url=path2+thumbs[i];$thumb.attr('src',url);$thumb.appendTo(ctn);console.log("thumbsloaded")}}
function loadThumbsPrev(){if(count>0){var $vel=$('#gallery_thumb_wrapper').width();$('#gallery_thumb_container').animate({left:"+="+$vel},500);count-=1}
var con=$('#gallery_thumb_container').css('left')}
function loadThumbsNext(){if(count<4){var $vel=$('#gallery_thumb_wrapper').width();$('#gallery_thumb_container').animate({left:"-="+$vel},500);count+=1}
var con=$('#gallery_thumb_container').css('left')}
function bindEvents(){$("#gallery_btn_prev>a").click(function(){loadImagesPrevious();loadImages()});$("#gallery_btn_next>a").click(function(){loadImagesNext();loadImages()});$('#gallery_thumb_wrapper').on('scroll',function(){loadImages()});$(document).keydown(function(e){switch(e.which){case 37:break;case 38:break;case 39:break;case 40:break;default:return}
e.preventDefault()});if($(".image_thumb")){$(".image_thumb").on("click",function(e){displaySelectedImage(e)})}
else{console.log("images attached too soon")}}
return{bindEvents:bindEvents}})();var mod_contact=(function(){var uploadedImagesCount=0,maxImageSize=2000048,maxImageCount=8;var $form=$('#contact_form'),$form_elements=$('#contact_form>input');var bindEvents=function(){document.querySelectorAll('.files').forEach(function(item,e){item.addEventListener('change',function(e){imageUploadValidation(e)})});document.getElementById("contact_form_send_btn").addEventListener("click",function(){},!1)}
function imageUploadValidation(event){var file=event.target.files[0],parent=event.target.parentElement;if(/\.(jpe?g|png|gif)$/i.test(file.name)){console.log("file_format_pass")}else{window.alert("bitte nur Bilder in folgenden Formaten: .jpg, .png, .gif");event.target.value=''}
if(file.size>maxImageSize){window.alert("Bitte ein kleineres Bild wählen");event.target.value=''}else{var reader=new FileReader();reader.onloadend=function(){parent.style.backgroundImage='url("'+reader.result+'")';parent.style.backgroundSize='cover'};if(file){reader.readAsDataURL(file)}}}
function validateForm(){var allFieldsFilled=!1,noFilesAttached=!0;var $errorElements=[];$('#contact_left').find(':input').each(function(index,element){if($(element).val()==""){$errorElements.push($(element))}else{console.log($(element).val())}})
$('#contact_right').find(':input').each(function(index,element){if($(element).val()!=""){noFilesAttached=!1}})
if($errorElements.length<=0){allFieldsFilled=!0}else{allFieldsFilled=!1;console.log($errorElements)}
if(allFieldsFilled&&!noFilesAttached){}else{if(!allFieldsFilled){alert("Bitte alle Felder ausfüller!")}
if(noFilesAttached){alert("Bitte Bilder von der Stelle und dem Tattoo auswählen!")}
event.preventDefault()}
console.log("validated")}
return{bindEvents:bindEvents,validateForm:validateForm}})();var mod_footer=(function(){var expanded=!1,footerData={};var $footerExp=$('#foot_footer'),$footerNavigation=$('#footer_navigation'),$footerContent=$('#footer_content'),$footerBtnImp=$('#footer_btn_impressum');$.ajax({url:"assets/text/footer.json",dataType:"json",success:function(response){footerData=response;bindData()}});function bindData(data){$footerContent.find('div').html(data)}
function bindEvents(){$footerBtnImp.click(function(event){bindData(footerData.impressum);$footerExp.toggleClass("footer_expand");$footerNavigation.toggleClass("footer_navigation_top");$footerContent.toggleClass("hidden");$footerBtnImp.toggleClass("footer_link_active");expanded!=expanded})};return{bindEvents:bindEvents}})();$(window).on('load',function(){app.init()})